name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci # Equivalent to npm install
    - run: npm run build

    #Post to mybells.github.io/master
    - name: Deploy mybells.github.io/master
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        TARGET_REPO: discord-buttons/docs-multilingual #Can create a new mybells.github.io warehouse and publish it to the master
        PUBLISH_BRANCH: master
        PUBLISH_DIR: docs/.vuepress/dist
      with:
          emptyCommits: false

    # #Post to MyBlog/gh-pages View https://mybells.github.io/MyBlog/, you need to modify the base configuration to MyBlog, modify the image path
    # - name: Deploy MyBlog/gh-pages
    #   uses: peaceiris/actions-gh-pages@v2
    #   env:
    #     ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    # PUBLISH_BRANCH: gh-pages #You can also create a new gh-pages branch in the MyBlog of this project. The name must be gh-pages so that the github page setting can recognize this branch, and other names cannot be recognized. https://help.github.com/cn/github/working-with-github-pages/creating-a-github-pages-site#creating-your-site
    #     PUBLISH_DIR: docs/.vuepress/dist
    #   with:
    #       emptyCommits: false
